### Numpy in Python

In [1]:
import numpy as np

In [3]:
## Create an array using numpy
## Creating 1D array 
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
print(arr.shape)
print(arr)

(1, 5)
[[1 2 3 4 5]]


In [11]:
arr.reshape((1,5)) # this means 1 row 5 columns
print(arr.shape)
print(arr)

(1, 5)
[[1 2 3 4 5]]


In [14]:
## Creating 2D arrays
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [20]:
arr = np.arange(0,10,2)
print(arr)
arr.reshape(5,1)

[0 2 4 6 8]


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
## creating array with ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
## Identity Matrix -> only diagonals will we ones
np.eye((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
## Attributes of numpy arrays
arr = np.array([[1,2,3,4],[5,6,7,8]])

print("Array :\n",arr)
print("Shape : ",arr.shape)
print("No of Dimensions : ",arr.ndim)
print("Size (No of elements) : ", arr.size)
print("Data Type : ",arr.dtype)
print("Item Size in Bytes : ",arr.itemsize)


Array :
 [[1 2 3 4]
 [5 6 7 8]]
Shape :  (2, 4)
No of Dimensions :  2
Size (No of elements) :  8
Data Type :  int64
Item Size in Bytes :  8


In [27]:
## Numpy Vectorized Operations
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
##Element wise Addition
print("Addition : ",arr1+arr2)
##Element wise Subtraction
print("Subtraction : ",arr1-arr2)
## Element wise Multiplication
print("Multiplication : ",arr1*arr2)
## Element wise Division 
print("Division : ",arr1/arr2)

Addition :  [ 6  8 10 12]
Subtraction :  [-4 -4 -4 -4]
Multiplication :  [ 5 12 21 32]
Division :  [0.2        0.33333333 0.42857143 0.5       ]


In [29]:
## Universial Functions
arr = np.array([1,2,3,4,5,6])
## square root
print(np.sqrt(arr))
## Exponentional
print(np.exp(arr))
## Sine
print(np.sin(arr))
## Log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [31]:
## Slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
## Pick up elements 7 8 11 12
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [34]:
## Pick 3 4 7 8
arr[:2,2:]

array([[3, 4],
       [7, 8]])

In [35]:
## Pick 6 7 10 11
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [37]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
arr[0,0] =100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
## make all second row and third row elements to 100
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [42]:
## Statistical Concepts --Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5,6])
## Caluclating Mean and Standard Deviation 
mean = np.mean(data)
std_dev = np.std(data)
## Normalize the data
normalized_data = (data-mean)/std_dev
print(normalized_data)


[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [44]:
 ## for mean
 print(np.mean(arr))
 ## for median
 print(np.median(arr))
 ## for standard deviation
 print(np.std(arr))
 ## variance
 print(np.var(arr))

75.75
100.0
42.00421605823238
1764.3541666666667


In [45]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
data[(data>5) & (data<8)]

array([6, 7])